### ISSUE TITLE
Feature request collection

### ISSUE THREAD

**Issue by andi34** [andreknieriem/photobooth#68]
# Please use this "issue" for feature requests. Starting post will be updated with your suggestions.

**Feature added**
- [X] frame around the picture for printing (v1.8.1)
- [X] photo collage (v1.8.1)
- [X] text overlay for photo printing (https://github.com/andreknieriem/photobooth/issues/9) ( @vdubuk , v1.8.2 )
- [X] initial theme support: switch between default and blue-gray theme via config (v1.8.2 )
- [X] print confirmation ( @flighter18 , @msmedien ) (https://github.com/andreknieriem/photobooth/issues/44) (v1.8.3)
- [X] polaroid effect  (v1.8.3)
- [X] Hidden shortcut to admin settings (@vdubuk ) (v1.8.3)
- [X] stop livepreview at countdown to allow using PiCamera to take a picture (v1.8.3)
- [X] relative path to allow running Photobooth from subfolder (v1.9.0)
- [X] responsive theme (thanks to @sualko )  (v1.9.0)
- [X] gallery standalone (localhost/gallery.php) (https://github.com/andreknieriem/photobooth/issues/55) (v2.0.0-alpha)
- [X] Delete / Remove picture after picture was taken and displayed on the screen  (v2.0.0-alpha)
- [X] change style via admin panel (v2.0.0-alpha)
- [X] option to enable CUPS button  (v2.0.0-alpha)
- [X] specify trigger keys via config/admin panel (v2.0.0-alpha)
- [X] option to force use a buzzer (v2.0.0-alpha)
- [X] option to resize and crop image by center at print (https://github.com/andreknieriem/photobooth/issues/82) (v2.0.0-alpha)
- [X] Switch to a css ribbon for "Fork Me" (v2.0.0-alpha)

**Ready for review**

**Work in progress (WIP)**
- Main Css Styling in Admin Panel (https://github.com/andreknieriem/photobooth/issues/104)

**Help wanted**
- [ ] download from gallery instead QR Code (https://github.com/andreknieriem/photobooth/issues/7)
- [ ] take 10 second videos/gifs (https://github.com/andreknieriem/photobooth/issues/35)
- [ ] Live-Cam Wallpaper or as Countdown Background via admin panel/config (https://github.com/andreknieriem/photobooth/issues/98)
- [ ] Camera profiles with predefined config (https://github.com/andreknieriem/photobooth/issues/99)

**Declined**
- button for shutdown or restart in admin- or user-page ( https://github.com/andreknieriem/photobooth/issues/100 )

**Comment by thymon13** [comment]
## Bouton on gallery  <h2>

The buttons on the photos from the gallery are too small and especially unsightly.

![11](https://user-images.githubusercontent.com/18228022/64545009-4d448700-d328-11e9-9974-47df993dc71d.jpg)

Would it be possible to enlarge them?
It would be best to have them in the middle of the picture. 
CSS buttons that appear and disappears when click on the photo. ?

like this for exemple :
![GitHub Logo](http://designgrapher.com/wp-content/uploads/2015/08/CSS3-Button-Examples4.jpg)
Format: ![Alt Text](url)

**Comment by thymon13** [comment]
## QR Code Pop'up not resized <h2>

I use a 9.6" touche pad. And the QR code is truncated.
I'have try with "false" ou "true" in my config for enable or not the mobile view. 
No change.

![12](https://user-images.githubusercontent.com/18228022/64545676-774a7900-d329-11e9-855f-2760db4f04ae.jpg)

**Comment by andi34** [comment]
> ## QR Code Pop'up not resized
> 
> I use a 9.6" touche pad. And the QR code is truncated.
> I'have try with "false" ou "true" in my config for enable or not the mobile view.
> No change.
> 
> ![12](https://user-images.githubusercontent.com/18228022/64545676-774a7900-d329-11e9-855f-2760db4f04ae.jpg)
@thymon13 https://github.com/andreknieriem/photobooth/issues/22


> ## Bouton on gallery
> 
> The buttons on the photos from the gallery are too small and especially unsightly.
> 
> ![11](https://user-images.githubusercontent.com/18228022/64545009-4d448700-d328-11e9-9974-47df993dc71d.jpg)
> 
> Would it be possible to enlarge them?
> It would be best to have them in the middle of the picture.
> CSS buttons that appear and disappears when click on the photo. ?
> 
> like this for exemple :
> ![GitHub Logo](https://camo.githubusercontent.com/590f17c1224dbf2b7ee5fe8c6c4f433449e94b56/687474703a2f2f64657369676e677261706865722e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031352f30382f435353332d427574746f6e2d4578616d706c6573342e6a7067)

This is also a design thing and not a feature itself.

**Comment by thymon13** [comment]
## Chroma Keying <h2>

I tested this function. Thats work perfectly.
But is it possible to use a picture background by default ? Instead of choose them in gallery -> select photo -> select function --> select background...

**Comment by andi34** [comment]
> ## Chroma Keying
> I tested this function. Thats work perfectly.
> But is it possible to use one picture background by default ? Instead of choose them in gallery -> select photo -> select function --> select background...
> 
> Example : Corporation event with Enterprise Logo in background by default...

You can adjust the source for your needs https://github.com/andreknieriem/photobooth/blob/master/chroma_keying/index.php#L51

**Comment by thymon13** [comment]
> This is also a design thing and not a feature itself.
@andi34 really ? :sob: :sob:

**Comment by thymon13** [comment]
I found anothers error for french translation...

**Comment by thymon13** [comment]
>you can adjust the source for your needs 
https://github.com/andreknieriem/photobooth/issues/68#issuecomment-529620150

I think my question is not clear.  When you take a picture the result is with the green background.  and you have to go to the gallery to choose the background you want to incorporate.  While it would be nice to have the result directly when the picture is taken.

**Comment by andi34** [comment]
That's nothing I am going to make an option. You can take a look at the chroma_keying source and modify the takePic.php for it, or use the new frame function (can also be added to takePic.php to apply the frame directly).

**Comment by andi34** [comment]
> > This is also a design thing and not a feature itself.
> 
> @andi34 really ?  
> So I open a design issue ?
Could also be part of the responsive design.
I am not able to implement every feature request myself (I've a full time job as a medical assistant and still learning js, php etc). Everyone is welcome to adjust the source for his/her needs and send a Pullrequest with useful changes (sure, I can make it clean commits in the end as I have a lot of experience with git).

Going to write a quick "how to submit code changes" soon.

**Comment by andi34** [comment]
> I found anothers errors for french translation...

Fork latest source, update the language file and send me a link for it. Maybe there's more to be adjusted?

**Comment by thymon13** [comment]
Ok thank you Andi34 for your answer.

**Comment by andi34** [comment]
@thymon13 maybe useful for you until ready:
```
git fetch https://github.com/andi34/photobooth private
git cherry-pick d317f58d95752ac585c8e2545ef24957ceb11a4c
git cherry-pick 9dab3dfae43342952ba5f6db85c5123aa3869c0b
git cherry-pick 250172ae175e6f815375335dcce566b840ad7bb2
```

**Comment by thymon13** [comment]
news private fetch for what ?

and how you commit ?
```
git cherry-pick d317f58d95752ac585c8e2545ef24957ceb11a4c
error: Your local changes to the following files would be overwritten by merge:
	resources/css/style.css
	resources/js/core.js
	resources/sass/style.scss
Please commit your changes or stash them before you merge.
Aborting
fatal: cherry-pick failed
```

**Comment by andi34** [comment]
This would create a commit with your made changes, yes. After that you can cherry-pick

**Comment by thymon13** [comment]
@andi34 
I'm really sorry but I do not understand anything

```
git cherry-pick d317f58d95752ac585c8e2545ef24957ceb11a4c
error: your local changes would be overwritten by cherry-pick.
hint: commit your changes or stash them to proceed.
fatal: cherry-pick failed
```

**Comment by andi34** [comment]
```
git cherry-pick --abort
git add --all
git commit -a -m "My local changes"
```
After that it should work. You'll only have conflicts at cherry-pick if you've modified the source at the same places already.

**Comment by thymon13** [comment]
@andi34  ok it's done

**Comment by andi34** [comment]
Maybe the adjustments for smaller device helps you a little bit

**Comment by thymon13** [comment]
Well no... :cry:

look : https://youtu.be/J8yeS-4Nu7s

**Comment by andi34** [comment]
What's your resolution?
You could try to adjust the ```@media (max-width: 800px)``` inside the style.css

**Comment by thymon13** [comment]
1280x800px
I will test it, thx

**Comment by vdubuk** [comment]
Hi @andi34 
Text on print, I do not know how to combine into repository, bur here is the code ive used 

print.php   after  $status = false;
`
// text on print variables -start
$fontsize = $config['fontsize']; 

$fontlocx = $config['locationx'];
$fontlocy = $config['locationy'];
$linespacing = $config['linespace'];
$fontrot = $config['rotation'];
$line1text = $config['textonprint']['line1'];
$line2text = $config['textonprint']['line2'];
$line3text = $config['textonprint']['line3'];
// text on print variables -end
`
after   imagecopyresized($print, $code, $width, 0, 0, 0, ($height / 2), ($height / 2), imagesx($code), imagesy($code));
`           // text on image - start
            if($config['is_textonprint'] == true) {
            $fontcolour = imagecolorallocate($print, 0, 0, 0);  // colour of font
            imagettftext ($print, $fontsize, $fontrot, $fontlocx, $fontlocy, $fontcolour, 'resources/fonts/GreatVibes-Regular.ttf' , $line1text);
            imagettftext ($print, $fontsize, $fontrot, $fontlocx, $fontlocy + $linespacing, $fontcolour, 'resources/fonts/GreatVibes-Regular.ttf' , $line2text);
            imagettftext ($print, $fontsize, $fontrot, $fontlocx, $fontlocy + ($linespacing *2), $fontcolour, 'resources/fonts/GreatVibes-Regular.ttf' , $line3text);
            }
            //text on image - end
`
in admin/index.php add
`// text print start
		'textonprint' => [
			'is_textonprint' => [
				'type' => 'checkbox',
				'name' => 'is_textonprint',
				'value' => $config['is_textonprint']
			],
			'line1' => [
				'type' => 'input',
				'placeholder' => 'line 1',
				'name' => 'textonprint[line1]',
				'value' => $config['textonprint']['line1']
			],
			'line2' => [
				'type' => 'input',
				'placeholder' => 'line 2',
				'name' => 'textonprint[line2]',
				'value' => $config['textonprint']['line2']
			],
			'line3' => [
				'type' => 'input',
				'placeholder' => 'line 3',
				'name' => 'textonprint[line3]',
				'value' => $config['textonprint']['line3']
			],
			'locationx' => [
				'type' => 'input',
				'placeholder' => 'locationx',
				'name' => 'locationx',
				'value' => $config['locationx']
			],
			'locationy' => [
				'type' => 'input',
				'placeholder' => 'locationy',
				'name' => 'locationy',
				'value' => $config['locationy']
			],
			'rotation' => [
				'type' => 'input',
				'placeholder' => 'rotation',
				'name' => 'rotation',
				'value' => $config['rotation']
			],
			'fontsize' => [
				'type' => 'input',
				'placeholder' => 'fontsize',
				'name' => 'fontsize',
				'value' => $config['fontsize']
			],
			'linespace' => [
				'type' => 'input',
				'placeholder' => 'linespace',
				'name' => 'linespace',
				'value' => $config['linespace']
			],
		],
		// text print end
`
in lang/en.js  (sorry ive not been able to add German or French) add

"textonprint": "Add Text to Print",
	"is_textonprint": "Text on print",
	"textonprint_line1": "Text for line 1",
	"textonprint_line2": "Text for line 2",
	"textonprint_line3": "Text for line 3",
	"textonprint_locationx": "X Coordinate",
	"textonprint_locationy": "Y Coordinate",
	"textonprint_rotation": "Text rotation",
	"textonprint_linespace": "Line spacing",
	"textonprint_fontsize": "Font size"

**Comment by andi34** [comment]
@vdubuk great!
You're on latest 1.8.1 branch?
You've a clone on your git?

Easiest might be:
```
git config core.fileMode false
git add --all
git commit -a -m "Add print text on pictures"
git format-patch-1
```
Now open the generated patch file and create a new gist here: https://gist.github.com/ and add the content of the patch file there and share the link to the gist.

**Comment by vdubuk** [comment]
> You're on latest 1.8.1 branch?

erm.. how do i check branch.

I made a clean install of andreknieriem/photobooth this morning

**Comment by andi34** [comment]
```
git log --oneline
```
This will show latest commits on your branch. If you clean cloned this morning you are and only need to run mentioned commands in terminal (cd to photobooth source first).

**Comment by andi34** [comment]
After the ```git commit -a -m "Bla"``` you can also do this:
``` git checkout -b printtext
git push https://github.com/vdubuk/photobooth HEAD: printtext```
This will create a new branch with your changes included on your clone.

**Comment by thymon13** [comment]
> What's your resolution?
> You could try to adjust the `@media (max-width: 800px)` inside the style.css

Forget about it, I found it why.
I did not want to see the web browser address bar. I have install an app for that.
Because when I test with Google Chrome, works.

sorry for any wasted time

**Comment by andi34** [comment]
> @andi34
> 
> > What's your resolution?
> > You could try to adjust the `@media (max-width: 800px)` inside the style.css
> 
> Forget about it, I found it why.
> I did not want to see the web browser address bar. I have install an app for that.
> Because when I test with Google Chrome, works.
> 
> sorry for any wasted time

Start in kiosk mode?
https://github.com/andi34/photobooth#kiosk-mode

**Comment by thymon13** [comment]
@andi34 
I can't, i use a Android Tablet...
I am looking for how to modify the default web browser to use Google chrome

**Comment by andi34** [comment]
@vdubuk thanks a lot! i've done some small adjustments.

@thymon13 could you do the french and spanish translation and post them for me?
i'll take care about german later.

https://github.com/andi34/photobooth/commit/742320da84c0c73ac16461e5c0175a4e9029aa72

**Comment by andi34** [comment]
- [ ]  initial theme support (switch between default and bluegrey theme via config) https://github.com/andi34/photobooth/commit/d58094697d60a89bf8b0800bd74aec11686cbb3e (translation need to be done)

**Comment by thymon13** [comment]
@andi34 
French translation it is done.
Spanish translation : 
I'm waiting for my wife because she's a Spanish teacher 🤣

**Comment by andi34** [comment]
Thanks @thymon13 , applied: https://github.com/andi34/photobooth/commit/a6502618fd539ce478571690251565fe83f5de90

Could you also check the theme support translation?

**Comment by vdubuk** [comment]
would it be possible to use PiCamera for Preview and Photo ?

looking at apache error logs it seems that when using the PiCamera for Preview it cannot be accessed in the command line to take Photo and therefore and error happens. 

Would it be possible to stop the Preview just before the Photo function to take the photo is called?

**Comment by andi34** [comment]
Should be possible to stop the stream once countdown is called, but not sure how to stop the stream

**Comment by thymon13** [comment]
@andi34 
all is done now :)

**Comment by andi34** [comment]
No problem and thanks :)
I'll take care of it tomorrow if I am up early enough :)

**Comment by andi34** [comment]
Thanks @vdubuk for your implementation.
Thanks @thymon13 for the translation :)

- [X] text overlay for photo printing ( @vdubuk , v1.8.2 )
- [X] initial theme support: switch between default and bluegrey theme via config (v1.8.2 )

Both merged :)

**Comment by msmedien** [comment]
Besteht die Möglichkeit ein fest einprogrammiertes "Overlay" für den/die Drucken-Buttons zu implementieren?

Immer wenn die Gäste etwas drucken möchten, wird zum Teil mehrfach gedrückt, da auf dem Bildschirm nichts angezeigt wird. Ich habe daher die angehangene Lösung gefunden, welche sehr gut funktioniert und in der Struktur schön einfach ist. - Das Problem ist halt nur das ich es bei jedem Update neu einbinden muss. Dabei würde es sicherlich mehreren Leuten helfen. (Bzw. den Gästen)

Als Erweiterung wäre es cool wenn man den angezeigten Text in der Sprachdatei anpassen könnte. :)

[Druckbenachrichtung.txt](https://github.com/andreknieriem/photobooth/files/3615925/Druckbenachrichtung.txt)

**Comment by flighter18** [comment]
Hi @msmedien 
Ein Lösung fur dein "Problem" ist in arbeit.  Dazu gibt es auch ein "To Do". Du findest es unter folgendem Link findest:
https://github.com/andi34/photobooth/issues/20#issuecomment-531187459

Hier noch das Beispiel Video für die implementierte Lösung.
https://youtu.be/NTxXxTOfN8U

Möchtest du die Implementation jetzt schon haben, kannst du dieses Repo Clonen:
https://github.com/flighter18/photobooth/tree/printconfirm

### ACHTUNG Branch heisst printconfirm

**Comment by andi34** [comment]
> Besteht die Möglichkeit ein fest einprogrammiertes "Overlay" für den/die Drucken-Buttons zu implementieren?
> 
> Immer wenn die Gäste etwas drucken möchten, wird zum Teil mehrfach gedrückt, da auf dem Bildschirm nichts angezeigt wird. Ich habe daher die angehangene Lösung gefunden, welche sehr gut funktioniert und in der Struktur schön einfach ist. - Das Problem ist halt nur das ich es bei jedem Update neu einbinden muss. Dabei würde es sicherlich mehreren Leuten helfen. (Bzw. den Gästen)
> 
> Als Erweiterung wäre es cool wenn man den angezeigten Text in der Sprachdatei anpassen könnte. :)
> 
> [Druckbenachrichtung.txt](https://github.com/andreknieriem/photobooth/files/3615925/Druckbenachrichtung.txt)

Danke für die Anregung. Ich habe noch nicht geschafft neben Vollzeitjob und Umzugsstress den Code selbst zu testen und anzupassen auf die einzelnen Sprachen, ist aber auf meiner Liste und spätestens nächste Woche sollte ich Luft dafür haben.

Wenn du dich mit git etwas auskennst einfach cherry-picken, geht auch automatisiert per Script (gerne hänge ich dir heute Abend mein Script Mal an).

**Comment by andi34** [comment]
```
cd var/www/html
git fetch https://github.com/flighter18/photobooth printconfirm
git cherry-pick 22ae559d63cc2bc737449062b0aeb0246080f41a
git cherry-pick e41a760cd362f9de00d7eb6dcee54c5814f89d02
```
Nur drauf achten das du die Filemode Änderungen vorher ausgestellt hast im repo.
```
cd /var/www/html
git config core.fileMode false
sudo git config core.fileMode false
```

**Comment by andi34** [comment]
@msmedien gerade erst gerallt das du auch eine Implementierung hast 🤗
Diese Teste ich natürlich auch, finde die Idee gut auf externe Scripts zu verzichten wie es bei dir der Fall ist.

**Comment by andi34** [comment]
@msmedien I'll pushed your changes here for now. I'll make it one clean commit and do some adjustments within this week. https://github.com/andi34/photobooth/commits/dev

**Comment by andi34** [comment]
**Ready for review**
- [ ] print confirmation ( @flighter18 , @msmedien ): 
  https://github.com/andi34/photobooth/commit/3272cb7b96948d5aa9c6f6c353f392ddeebd87a2
  https://github.com/andi34/photobooth/commit/bc3daf1c571124bf483b9b84dbb13b6a7a2a5de9

**Comment by andi34** [comment]
> would it be possible to use PiCamera for Preview and Photo ?
> 
> looking at apache error logs it seems that when using the PiCamera for Preview it cannot be accessed in the command line to take Photo and therefore and error happens.
> 
> Would it be possible to stop the Preview just before the Photo function to take the photo is called?

Could you try to move this parts up a little bit?
https://github.com/andreknieriem/photobooth/blob/84b3c21647376f01e73c436682cd8466975979b0/resources/js/core.js#L123-L127

So it looks like:

    // take Picture
    public.takePic = function (photoStyle) {
        processing = true;
        if (isdev) {
            console.log('Take Picture:' + photoStyle);
        }
        if(useVideo){
            var track = public.stream.getTracks()[0];
            track.stop();
            $('video').hide();
        }
        setTimeout(function () {
	    if ((photoStyle=='photo')){
                $('#counter').text('');
                $('.spinner').show();
                $('.loading').text(L10N.busy);
            } else {
```

**Comment by thymon13** [comment]
@andi34 
Nice Tutorial ! Need to add this en (FAQ)

I tested "Print Confirmation" Soooooo great ! Works perfectly

**Comment by andi34** [comment]
**Feature added**
- [X] print confirmation ( @flighter18 , @msmedien )

Merged :smiley: 
https://github.com/andreknieriem/photobooth/commit/ab2ebf3f551d194187b9918a926ad75aa70468fd
https://github.com/andreknieriem/photobooth/commit/58fb383570e57acaa654e5c4a8b052d21efeb7d6

Thanks everyone :+1:

**Comment by andi34** [comment]
**Ready for review**
- [ ] polaroid effect: https://github.com/andi34/photobooth/commit/df3b84dcabdeeb3c0a05d8d4f944221ecc2da1bd

Might need adjustment to also use $filename_orig = $filename_tmp;
 
change from
```
if($_POST['style'] === 'photo') {
	$filename_orig = $filename_photo;
	$use_filter = false;
} else {
	$filename_orig = $filename_tmp;
	$use_filter = false;
}
if(!empty($_POST) && !($_POST['filter'] === 'imgPlain')) {
	$filename_orig = $filename_tmp;
	$use_filter = true;
	$imgfilter = $_POST['filter'];
}
```
to
```
if($_POST['style'] === 'photo') {
	$filename_orig = $filename_photo;
	$use_filter = false;
} else {
	$filename_orig = $filename_tmp;
	$use_filter = false;
}

if($config['polaroid_effect'] === true) {
	$filename_orig = $filename_tmp;
}

if(!empty($_POST) && !($_POST['filter'] === 'imgPlain')) {
	$filename_orig = $filename_tmp;
	$use_filter = true;
	$imgfilter = $_POST['filter'];
}
```

Examples:
![20190918_194459](https://user-images.githubusercontent.com/6080900/65174379-17eb1800-da51-11e9-9574-9ac8771bfdfb.jpg)

![20190918_200955](https://user-images.githubusercontent.com/6080900/65174388-1ae60880-da51-11e9-914b-8a33dd3be7ff.jpg)

**Comment by andi34** [comment]
Btw. You can follow the steps mentioned here again to test this new feature:
https://github.com/andreknieriem/photobooth/issues/68#issuecomment-531877199

If you've already added my fork as remote you only need to run
```
cd /var/www/HTML
git fetch andi34
git checkout andi34/dev
```

**Comment by vdubuk** [comment]
> Could you try to move this parts up a little bit?
> https://github.com/andreknieriem/photobooth/blob/84b3c21647376f01e73c436682cd8466975979b0/resources/js/core.js#L123-L127
> 
> So it looks like:
> 
> ```
>     // take Picture
>     public.takePic = function (photoStyle) {
>         processing = true;
>         if (isdev) {
>             console.log('Take Picture:' + photoStyle);
>         }
>         if(useVideo){
>             var track = public.stream.getTracks()[0];
>             track.stop();
>             $('video').hide();
>         }
>         setTimeout(function () {
> 	    if ((photoStyle=='photo')){
>                 $('#counter').text('');
>                 $('.spinner').show();
>                 $('.loading').text(L10N.busy);
>             } else {
> ```

This solution worked for me, thank you @andi34

**Comment by andi34** [comment]
Thanks for the feedback @vdubuk .
@andreknieriem it's fine to submit the code change or it's a wanted behavior to stop the preview at the point it is?

**Comment by andreknieriem** [comment]
Can be changed ;)

**Comment by vdubuk** [comment]
Kiosk Mode  feature request

When running app in Kiosk mode it can be difficult to get to the Admin/settings page.  

therefore I would like to suggest of having a hidden shortcut to get to settings

index.php  around line 274 after the print mesg div

````
        
	<!-- added div --> 

	<div id="adminsettings" >
		<div style="position:absolute; bottom:0; right:0;"><img src="/resources/img/spacer.png" 
        alt="adminsettings" ondblclick="adminsettings()"></div>
	</div>  
 
	<script type="text/javascript" src="/resources/js/adminshortcut.js"></script> 

	<!-- end -->

	
     
```
create new file aresources/js/adminshortcut.js 

```
var admincount = 0;
		function countreset() {
			admincount = 0;
		}
		function adminsettings() {
			if (admincount == 3) {
				window.location.href="admin/index.php";
			}
			console.log(admincount);
			admincount++;
			setTimeout(countreset, 10000);
		}

```

add spacer.png to resources/img/ 
![spacer](https://user-images.githubusercontent.com/4080228/65237329-5ecd2200-dad2-11e9-9b86-efa306e6558d.png)

**Comment by andi34** [comment]
> Kiosk Mode feature request
> 
> When running app in Kiosk mode it can be difficult to get to the Admin/settings page.
> 
> therefore I would like to suggest of having a hidden shortcut to get to settings
> 
> index.php around line 274 after the print mesg div
> 
> ```
>         
> 	 
> 
> 	<div id="adminsettings" >
> 		<div style="position:absolute; bottom:0; right:0;"><img src="/resources/img/spacer.png" 
>         alt="adminsettings" ondblclick="adminsettings()"></div>
> 	</div>  
>  
> 	<script type="text/javascript" src="/resources/js/adminshortcut.js"></script> 
> 
> 	
> 
> 	
>      
> ```
> create new file aresources/js/adminshortcut.js 
> 
> ```
> var admincount = 0;
> 		function countreset() {
> 			admincount = 0;
> 		}
> 		function adminsettings() {
> 			if (admincount == 3) {
> 				window.location.href="admin/index.php";
> 			}
> 			console.log(admincount);
> 			admincount++;
> 			setTimeout(countreset, 10000);
> 		}
> 
> ```
> 
> add spacer.png to resources/img/ 
> 
> ![spacer](https://user-images.githubusercontent.com/4080228/65237830-51646780-dad3-11e9-8adb-0293086f88fb.png)
> ```

works fine. ready for testing in my dev branch

**Comment by andi34** [comment]
Double tap in the right bottom corner until the admin page appears (for me it takes 4 double clicks in chrome) 

![Screenshot_2019-09-19_19-28-11](https://user-images.githubusercontent.com/6080900/65266922-4ed63200-db14-11e9-8f3d-e9bd01706b23.png)

**Comment by andi34** [comment]
https://github.com/andi34/photobooth/commit/6b926f8d9118147e2f5679d647fac88fcdc30c28

Jemand eine Idee?

**Comment by andi34** [comment]
Found the issue. config.json is ignored... Config.inc.php/my.config.inc.php is used only.
Need to find out how to solve it.
Maybe someone can help?

**Comment by andi34** [comment]
Found a solution. Moved the php files out of the chroma_keying folder:
https://github.com/andreknieriem/photobooth/commit/f607a4196dbe60def3a0a6f3af0002ec9da1324f

**Comment by sualko** [comment]
What is the purpose of this issue? Github provides already a nice overview :wink: : https://github.com/andreknieriem/photobooth/labels/enhancement

**Comment by andi34** [comment]
Purpose was to have one thread/issue for feature request instead having 100 "issues"

**Comment by sualko** [comment]
The advantage of having 100 issues is, that you can reference them inside of issues, pull requests and commits. You have a clear history of an issue, can subscribe to the further development and you can discuss details. But both ways are applicable.

**Comment by msmedien** [comment]
Da das Green-Screen-Feature jetzt läuft, frage ich mich jedoch ob es nicht einen benutzerfreundlicheren Weg gibt dieses zu bedienen...

1. Auf der Startseite den "Foto erstellen"-Button drücken
2. Countdown + Foto wird erstellt
3. Foto wird angezeigt inkl. der Auswahl der verschiedenen Hintergründen (ähnlich wie über die Gallerie-Funktion nur ohne "Drucken"- und "Schließen"-Button)
4. Hintergrund wählen und speichern (oder ein "Weiter"-Button)
5. Anzeige des fertigen Fotos inkl. der "normalen" Buttons (wie z.B. Gallerie, QR-Code, Neues Fotos etc. pp - So wie es jetzt auch ist nachdem das normale Foto geschossen wurde)

Natürlich nur wenn das Green-Screen-Feature aktiviert ist, ansonsten sollte über den Button ein ganz normales Foto gemacht werden. - Ggf. auch mit einem extra Button, wie bei der Collagen-Funktion.

**Comment by andi34** [comment]
Closing this thread as new feature request issues get opened instead posting requests here.
Use own issues which can be closed via Pullrequest if a feature is added.
